### ISSUE TITLE
iBeacons not found | Nexus 4/OnePlusOne

### ISSUE THREAD

**Issue by williamrijksen** [topgenorth/Estimotes-Xamarin#7]
Hello,

Maybe I do something wrong, but on my Nexus 4 and OnePlusOne no iBeacons where found when Ranging.
Here is my codebase : https://github.com/williamrijksen/Xamarinibeacontest.
I get no crashes or exceptions on my code. 
I see ranging is started, but it found 0 beacons. 

Can you help me please?

**Comment by topgenorth** [comment]
I'll take a look at and see what I can figure out. Might not be until the weekend.

**Comment by jamesmontemagno** [comment]
You did not specify a UUID: region = new EstimoteSdk.Region(BeaconId, null, null, null);  is in your code.

You MUST specify a UUID to scan for the. The beacon ID is just returned to you when you range a beacon. 

Find your UUID for your beacons:
region = new EstimoteSdk.Region(BeaconId, UUIDGoesHere, null, null);

**Comment by topgenorth** [comment]
@williamrijksen : did the advice provided by @jamesmontemagno solve your problem?
